---
- name: install Docker
  hosts: localhost
  become: true
  tasks:
    - name: apt update
      apt:
        update_cache: yes
    
    - name: Install prerequisites for Docker repository
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
    
    - name: add docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    
    - name: Remove specified repository from sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
        state: absent
    
    - name: add docker apt repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
        state: present
        update_cache: yes
      
    - name: install docker and it's dependencies
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    
    - name: start and enable docker daemon
      service:
        name: docker
        state: started
        enabled: yes
    